version: '3.3' 

services:

  registry:
    image: registry:2.8.0
    restart: always
    ports:
    - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['*']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=[HEAD,GET,OPTIONS,DELETE]
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=[true]
      - REGISTRY_STORAGE_DELETE_ENABLED='true'
    volumes:
      - ./registry:/var/lib/registry
    networks:
      - registry-net
    container_name: registry

  registry-ui:
    image: joxit/docker-registry-ui:2
    restart: always
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
      - CATALOG_ELEMENTS_LIMIT=1000
    networks:
      - registry-net
    container_name: registry-ui

networks:
    registry-net:

volumes:
    storage:
      driver: local

