version: '3.2'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: door
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: door_db
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: >
      bash -c "exec docker-entrypoint.sh mysqld && 
      mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /docker-entrypoint-initdb.d/dump.sql"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

