version: '3.2'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: taghi
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: taghi_db
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

